################################### English language #####################################
[en]
languageName = "EN"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
[en.params]
########### footer content ##########
footer_menu_left = "Autism-101"
footer_menu_middle = "Resources"
footer_menu_right = "Support"
footer_content = "Resources for newly diagnosed or self-identified Autistic people and those who think they might be."
