# main menu
[[main]]
name = "Home"
url = ""
weight = 1

# [[main]]
# weight = 4
# name = "Company"
# hasChildren = true

#   [[main]]
#   parent = "Company"
#   name = "About"
#   url = "about/"
#   weight = 1

#   [[main]]
#   parent = "Company"
#   name = "Team"
#   url = "team/"
#   weight = 4

#   [[main]]
#   parent = "Company"
#   name = "How It Works"
#   url = "how-it-works/"
#   weight = 8

#   [[main]]
#   parent = "Company"
#   name = "Career"
#   url = "career/"
#   weight = 9

#   [[main]]
#   parent = "Company"
#   name = "Career Details"
#   url = "career/sr-executive-service-assurance/"
#   weight = 10

# [[main]]
# weight = 6
# name = "Products"
# hasChildren = true
# [main.params]
# isMenuLarge = true

#   [[main]]
#   parent = "Products"
#   name = "CRM"
#   pre = "<i class='dropdown-icon fas fa-users'></i>"
#   post = "<small class='dropdown-subtitle'>Convert leads and close sales deals faster.</small>"
#   url = "products/product-1/"
#   weight = 1

#   [[main]]
#   parent = "Products"
#   name = "Help Desk"
#   pre = "<i class='dropdown-icon fas fa-dice-d6'></i>"
#   post = "<small class='dropdown-subtitle'>Software to deliver great customer support.</small>"
#   url = "products/product-2/"
#   weight = 2

#   [[main]]
#   parent = "Products"
#   name = "Workplace"
#   pre = "<i class='dropdown-icon fas fa-laptop-house'></i>"
#   post = "<small class='dropdown-subtitle'>Application built to improve productivity.</small>"
#   url = "products/product-3/"
#   weight = 3

#   [[main]]
#   parent = "Products"
#   name = "Analytics"
#   pre = "<i class='dropdown-icon fas fa-chart-bar'></i>"
#   post = "<small class='dropdown-subtitle'>Create custom reports from any data set.</small>"
#   url = "products/product-4/"
#   weight = 4

  # [[main]]
  # parent = "Products"
  # name = "View All Product"
  # pre = "<i class='dropdown-icon text-primary fas fa-arrow-right'></i>"
  # url = "products/"
  # weight = 5

# [[main]]
# weight = 13
# name = "Blog"
# hasChildren = true

#   [[main]]
#   parent = "Blog"
#   name = "Blog Posts"
#   url = "blog/"
#   weight = 3

#   [[main]]
#   parent = "Blog"
#   name = "Blog Details"
#   url = "blog/post-2/"
#   weight = 8

#   [[main]]
#   parent = "Blog"
#   name = "Elements"
#   url = "blog/post-1/"
#   weight = 9

#   [[main]]
#   parent = "Blog"
#   name = "Author"
#   url = "author/"
#   weight = 11

#   [[main]]
#   parent = "Blog"
#   name = "Author Details"
#   url = "author/awab-husameldin/"
#   weight = 12

[[main]]
weight = 15
name = "Pages"
hasChildren = true

#   [[main]]
#   parent = "Pages"
#   name = "Pricing"
#   url = "pricing/"
#   weight = 1

#   [[main]]
#   parent = "Pages"
#   name = "Case Studies"
#   url = "case-studies/"
#   weight = 4

#   [[main]]
#   parent = "Pages"
#   name = "Case Studies Details"
#   url = "case-studies/case-1/"
#   weight = 5

#   [[main]]
#   parent = "Pages"
#   name = "Contact"
#   url = "contact/"
#   weight = 10

  [[main]]
  parent = "Pages"
  name = "About"
  url = "about/"
  weight = 14

  # [[main]]
  # parent = "Pages"
  # name = "Autism FAQ"
  # url = "autism-faq/"
  # weight = 16

  [[main]]
  parent = "Pages"
  name = "Privacy Policy"
  url = "privacy-policy/"
  weight = 20

  [[main]]
  parent = "Pages"
  name = "Terms & Conditions"
  url = "terms-conditions/"
  weight = 24

[[main]]
name = "Contact"
url = "contact/"
weight = 30

[[main]]
weight = 6
name = "Resources"
hasChildren = true
[main.params]
isMenuLarge = true

  [[main]]
  parent = "Resources"
  name = "Newly Diagnosed"
  pre = "<i class='dropdown-icon fas fa-user-md'></i>"
  post = "<small class='dropdown-subtitle'>I've just been diagnosed or self-identified as autistic.</small>"
  url = "autism-resources-newly-diagnosed/"
  weight = 1
  
  [[main]]
  parent = "Resources"
  name = "I Might Be Autistic"
  pre = "<i class='dropdown-icon fas fa-portrait'></i>"
  post = "<small class='dropdown-subtitle'>So how can I tell?</small>"
  url = "i-might-be-autistic/"
  weight = 2

  [[main]]
  parent = "Resources"
  name = "Autistic Groups"
  pre = "<i class='dropdown-icon fas fa-users'></i>"
  post = "<small class='dropdown-subtitle'>Where to find other autistic people.</small>"
  url = "autistic-groups/"
  weight = 3

  # [[main]]
  # parent = "Resources"
  # name = "Autistic Answers"
  # pre = "<i class='dropdown-icon fas fa-dice-d6'></i>"
  # post = "<small class='dropdown-subtitle'>Where to go to find answers from actually autistic people.</small>"
  # url = "products/product-2/"
  # weight = 4

  [[main]]
  parent = "Resources"
  name = "Autism Education"
  pre = "<i class='dropdown-icon fas fa-book'></i>"
  post = "<small class='dropdown-subtitle'>Great books by autistic authors.</small>"
  url = "autism-education/"
  weight = 5

  [[main]]
  parent = "Resources"
  name = "Autism Functioning Labels"
  pre = "<i class='dropdown-icon fas fa-user-tag'></i>"
  post = "<small class='dropdown-subtitle'>Why they are not helpful.</small>"
  url = "autism-functioning-labels/"
  weight = 6

  # [[main]]
  # parent = "Resources"
  # name = "Person-first vs Identity-first"
  # pre = "<i class='dropdown-icon fas fa-person'></i>"
  # post = "<small class='dropdown-subtitle'>Which language is right?</small>"
  # url = "person-first-vs-identity-first/"
  # weight = 7

  [[main]]
  parent = "Resources"
  name = "Autism Glossary"
  pre = "<i class='dropdown-icon fas fa-book-reader'></i>"
  post = "<small class='dropdown-subtitle'>Common terms.</small>"
  url = "autism-glossary/"
  weight = 8

  [[main]]
  parent = "Resources"
  name = "Autism FAQ"
  pre = "<i class='dropdown-icon fas fa-circle-question'></i>"
  post = "<small class='dropdown-subtitle'>Frequently asked questions.</small>"
  url = "autism-faq/"
  weight = 9

[[main]]
weight = 13
name = "Autism Blog"
hasChildren = true

  [[main]]
  parent = "Autism Blog"
  name = "Blog Posts"
  url = "autism-blog/"
  weight = 3

  [[main]]
  parent = "Autism Blog"
  name = "Author"
  url = "author/"
  weight = 11


# footer menu left
[[footer_left]]
name = "About"
url = "about/"
weight = 1

[[footer_left]]
name = "Autism Blog"
url = "autism-blog/"
weight = 2

# [[footer_left]]
# name = "How It Works"
# url = "how-it-works/"
# weight = 3

# [[footer_left]]
# name = "Career"
# url = "career/"
# weight = 4


# footer menu middle
[[footer_middle]]
name = "Newly Diagnosed"
url = "autism-resources-newly-diagnosed/"
weight = 1

[[footer_middle]]
name = "I Might Be Autistic"
url = "i-might-be-autistic/"
weight = 2

[[footer_middle]]
name = "Autistic Groups"
url = "autistic-groups/"
weight = 3

# [[footer_middle]]
# name = "Autistic Answers"
# url = "products/product-2/"
# weight = 4

[[footer_middle]]
name = "Autism Education"
url = "autism-education/"
weight = 5

[[footer_middle]]
name = "Autism Functioning Labels"
url = "autism-functioning-labels/"
weight = 6

[[footer_middle]]
name = "Autism Glossary"
url = "autism-glossary/"
weight = 7

[[footer_middle]]
name = "Autism FAQ"
url = "autism-faq/"
weight = 8

# footer menu right
[[footer_right]]
name = "Autism FAQ"
url = "autism-faq/"
weight = 1

[[footer_right]]
name = "Contact"
url = "contact/"
weight = 2

[[footer_right]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 3

[[footer_right]]
name = "Terms & Conditions"
url = "terms-conditions/"
weight = 4