---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: heading
  label: Homepage
- type: document
  path: bigspring/content/english/_index.md
  label: Homepage (en)
- type: heading
  label: Autistic Groups
- type: document
  path: bigspring/content/english/autistic-groups/_index.md
  label: Autistic Group (en)
- type: directory
  path: bigspring/content/english/autistic-groups
  label: All Groups (en)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - new-group
- type: heading
  label: Author
- type: directory
  path: bigspring/content/english/author
  label: Author (en)
  create: all
  match: "*"
  templates:
  - new-author
- type: heading
  label: Blog
- type: document
  path: bigspring/content/english/blog/_index.md
  label: Blog (en)
- type: directory
  path: bigspring/content/english/blog
  label: Blog Posts (en)
  create: documents
  match: "**/*"
  exclude: _index.md
  templates:
  - post
- type: heading
  label: Others Page
- type: document
  path: bigspring/content/english/about.md
  label: About (en)
- type: document
  path: bigspring/content/english/autism-education.md
  label: Educations (en)
- type: document
  path: bigspring/content/english/faq.md
  label: FAQ (en)
- type: document
  path: bigspring/content/english/autism-functioning-labels.md
  label: Functioning Labels (en)
- type: document
  path: bigspring/content/english/i-might-be-autistic.md
  label: I Might Be Autistic (en)
- type: document
  path: bigspring/content/english/autism-resources-newly-diagnosed.md
  label: Newly Diagnosed (en)
- type: document
  path: bigspring/content/english/contact.md
  label: Contact (en)
- type: document
  path: bigspring/content/english/privacy-policy.md
  label: Privacy Policy (en)
- type: document
  path: bigspring/content/english/terms-conditions.md
  label: Terms & Conditions (en)
- type: heading
  label: All Pages
- type: directory
  path: bigspring/content
  label: All Pages
  create: all
  match: "**/*"
  exclude: _index.md
  templates:
  - new-page
- type: heading
  label: Configuration
- type: document
  path: bigspring/config/_default/config.toml
  label: Configuration
- type: document
  path: bigspring/config/_default/params.toml
  label: Parameters
- type: document
  path: config.toml
  label: Variables & Plugins
- type: document
  path: bigspring/config/_default/languages.toml
  label: Languages
- type: document
  path: bigspring/config/_default/menus.en.toml
  label: Menu (en)
- type: directory
  path: bigspring/i18n
  label: i18n Translations
  create: documents
  match: "**/*"
upload_dir: bigspring/assets/images
public_path: "/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.87.0
  preview_output_directory: public
  preview_docker_image: forestryio/hugo:latest
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
version: 0.87.0
